#!/usr/bin/env bash

# File paths
SETTINGS_FILE="$HOME/.config/hypr/settings.json"
WEATHER_SCRIPT="$HOME/.config/hypr/scripts/weather.sh"
ENV_FILE="$HOME/.config/hypr/scripts/quickshell/calendar/.env"

# Target configuration files
CONF_DIR="$HOME/.config/hypr/config"
TMPL_DIR="$HOME/.config/hypr/templates"

# Lua config -- what Hyprland actually reads (the .conf format is gone in 0.57).
SETTINGS_LUA="$CONF_DIR/settings.lua"
ENV_LUA="$CONF_DIR/env.lua"
AUTOSTART_LUA="$CONF_DIR/autostart_data.lua"
KEYBINDS_LUA="$CONF_DIR/keybinds_data.lua"
MONITORS_LUA="$CONF_DIR/monitors_data.lua"

# Legacy .conf output. Hyprland ignores these while hyprland.lua exists; they are kept
# only so `mv hyprland.lua hyprland.lua.off` remains a working rollback. Set to 0 (or
# delete the blocks) once 0.57 lands and the .conf tree is dropped for good.
LEGACY_CONF="${LEGACY_CONF:-1}"
SETTINGS_CONF="$CONF_DIR/settings.conf"
AUTOSTART_CONF="$CONF_DIR/autostart.conf"
ENV_CONF="$CONF_DIR/env.conf"
KEYBINDS_CONF="$CONF_DIR/keybindings.conf"
MONITORS_CONF="$CONF_DIR/monitors.conf"

ZSH_RC="$HOME/.zshrc"

# Ensure the required files and directories exist
mkdir -p "$CONF_DIR" "$TMPL_DIR" "$(dirname "$SETTINGS_FILE")" "$(dirname "$ENV_FILE")"
[ ! -f "$SETTINGS_FILE" ] && echo "{}" > "$SETTINGS_FILE"

CACHE_DIR="$HOME/.cache/settings_watcher"
mkdir -p "$CACHE_DIR"

compile_settings() {
    echo "Regenerating configurations from templates..."

    # Hash existing configs before any changes, split by monitor vs non-monitor.
    # This means a pure uiScale/wallpaperDir/weatherApiKey write never triggers a reload.
    OLD_NONMON_HASH=$(md5sum "$SETTINGS_LUA" "$KEYBINDS_LUA" "$AUTOSTART_LUA" "$ENV_LUA" \
                              "$SETTINGS_CONF" "$KEYBINDS_CONF" "$AUTOSTART_CONF" "$ENV_CONF" 2>/dev/null | md5sum)
    OLD_MON_HASH=$(md5sum "$MONITORS_LUA" "$MONITORS_CONF" 2>/dev/null | md5sum)

    # Read state from JSON (Using 'has' to safely parse booleans)
    LANG=$(jq -r '.language // "us"' "$SETTINGS_FILE")
    KB_OPT=$(jq -r '.kbOptions // "grp:alt_shift_toggle"' "$SETTINGS_FILE")
    WP_DIR=$(jq -r '.wallpaperDir // empty' "$SETTINGS_FILE")

    # Safely parse booleans so "false" doesn't trigger a fallback
    GUIDE_STARTUP=$(jq -r 'if has("openGuideAtStartup") then .openGuideAtStartup else true end' "$SETTINGS_FILE")

    PIC_DIR="$(xdg-user-dir PICTURES 2>/dev/null || echo "$HOME/Pictures")"
    VID_DIR="$(xdg-user-dir VIDEOS 2>/dev/null || echo "$HOME/Videos")"

    # Read the hardware variables injected by install.sh directly out of the JSON
    HW_ENV=$(jq -r '.hardwareEnvs[]? // empty' "$SETTINGS_FILE")

    # 1. Regenerate env.lua using the template
    echo "Regenerating env.lua..."
    sed -e "s|{{XDG_PICTURES_DIR}}|$PIC_DIR|g" \
        -e "s|{{XDG_VIDEOS_DIR}}|$VID_DIR|g" \
        -e "s|{{WALLPAPER_DIR}}|$WP_DIR|g" \
        -e "s|{{SCRIPT_DIR}}|$HOME/.config/hypr/scripts|g" \
        "$TMPL_DIR/env.lua.template" > "${ENV_LUA}.tmp"

    # Hardware injections arrive as legacy "env = NAME,value" lines; rewrite them as hl.env()
    awk -v hw="$HW_ENV" '
        function emit(line,   body, name, value, p) {
            body = line; sub(/^[[:space:]]*env[[:space:]]*=[[:space:]]*/, "", body)
            p = index(body, ","); if (p == 0) return
            name = substr(body, 1, p - 1); value = substr(body, p + 1)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", name); gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
            gsub(/\\/, "\\\\", value); gsub(/"/, "\\\"", value)
            printf "hl.env(\"%s\", \"%s\")\n", name, value
        }
        {
            if (index($0, "{{HARDWARE_ENV}}")) {
                if (hw != "") { n = split(hw, lines, "\n"); for (i = 1; i <= n; i++) if (lines[i] != "") emit(lines[i]) }
            } else print $0
        }' "${ENV_LUA}.tmp" > "$ENV_LUA"
    rm -f "${ENV_LUA}.tmp"

    # Sync ZSH_RC if Wallpaper Dir changed
    if [ -n "$WP_DIR" ] && [ -f "$ZSH_RC" ]; then
        sed -i "s|^export WALLPAPER_DIR=.*|export WALLPAPER_DIR=\"$WP_DIR\"|" "$ZSH_RC"
    fi

    # 2. Regenerate settings.lua using template
    echo "Regenerating settings.lua..."
    sed -e "s|{{KB_LAYOUT}}|$LANG|g" \
        -e "s|{{KB_OPTIONS}}|$KB_OPT|g" \
        "$TMPL_DIR/settings.lua.template" > "$SETTINGS_LUA"

    # 3. Regenerate the autostart command list
    echo "Regenerating autostart_data.lua..."
    {
        echo "-- ◈ AUTOSTART COMMANDS (AUTOGENERATED FROM SETTINGS.JSON)"
        echo "return {"
        jq -r '.startup[]? | "    \(.command // "" | @json),"' "$SETTINGS_FILE"
        # Evaluate the guide boolean natively in jq and output the line ONLY if it resolves to true
        if [[ $(jq -r 'if (if type == "object" and has("openGuideAtStartup") then .openGuideAtStartup else true end) then "yes" else "no" end' "$SETTINGS_FILE") == "yes" ]]; then
            echo "    \"bash -c 'sleep 1 && ~/.config/hypr/scripts/qs_manager.sh toggle guide'\","
        fi
        echo "}"
    } > "$AUTOSTART_LUA"

    # 4. Regenerate the keybind list. lib/binds.lua translates these specs into hl.bind()
    #    calls, so the Settings UI can keep writing legacy dispatcher names.
    echo "Regenerating keybinds_data.lua..."
    {
        echo "-- ◈ KEYBINDS (AUTOGENERATED FROM SETTINGS.JSON)"
        echo "return {"
        jq -r '.keybinds[]? | "    { type = \(.type // "bind" | @json), mods = \(.mods // "" | @json), key = \(.key // "" | @json), dispatcher = \(.dispatcher // "exec" | @json), command = \(.command // "" | @json) },"' "$SETTINGS_FILE"
        echo "}"
    } > "$KEYBINDS_LUA"

    # 5. Regenerate the monitor list
    echo "Regenerating monitors_data.lua..."
    {
        echo "-- ◈ MONITORS (AUTOGENERATED FROM SETTINGS.JSON)"
        echo "return {"
        jq -r '.monitors[]? | "    { output = \(.name // "" | @json), mode = \("\(.resW)x\(.resH)@\(.rate)" | @json), position = \("\(.x)x\(.y)" | @json), scale = \(.scale | tostring | @json)\(if .transform and .transform != 0 then ", transform = \(.transform)" else "" end) },"' "$SETTINGS_FILE"
        echo "}"
    } > "$MONITORS_LUA"

    # 6. Legacy .conf mirror, kept only as a rollback path (see LEGACY_CONF above)
    if [[ "$LEGACY_CONF" == "1" ]]; then
        sed -e "s|{{XDG_PICTURES_DIR}}|$PIC_DIR|g" \
            -e "s|{{XDG_VIDEOS_DIR}}|$VID_DIR|g" \
            -e "s|{{WALLPAPER_DIR}}|$WP_DIR|g" \
            -e "s|{{SCRIPT_DIR}}|$HOME/.config/hypr/scripts|g" \
            "$TMPL_DIR/env.conf.template" > "${ENV_CONF}.tmp"
        awk -v hw="$HW_ENV" '{
            if (index($0, "{{HARDWARE_ENV}}")) { print hw } else { print $0 }
        }' "${ENV_CONF}.tmp" > "$ENV_CONF"
        rm -f "${ENV_CONF}.tmp"

        sed -e "s|{{KB_LAYOUT}}|$LANG|g" \
            -e "s|{{KB_OPTIONS}}|$KB_OPT|g" \
            "$TMPL_DIR/settings.conf.template" > "$SETTINGS_CONF"

        cp "$TMPL_DIR/autostart.conf.template" "$AUTOSTART_CONF"
        jq -r '.startup[]? | "exec-once = \(.command)"' "$SETTINGS_FILE" >> "$AUTOSTART_CONF"
        if [[ $(jq -r 'if (if type == "object" and has("openGuideAtStartup") then .openGuideAtStartup else true end) then "yes" else "no" end' "$SETTINGS_FILE") == "yes" ]]; then
            echo "exec-once = bash -c 'sleep 1 && ~/.config/hypr/scripts/qs_manager.sh toggle guide'" >> "$AUTOSTART_CONF"
        fi

        cp "$TMPL_DIR/keybinds.conf.template" "$KEYBINDS_CONF"
        jq -r '.keybinds[]? | "\(.type // "bind") = \(.mods // ""), \(.key // ""), \(.dispatcher // "exec")\(if .command and .command != "" then ", \(.command)" else "" end)"' "$SETTINGS_FILE" >> "$KEYBINDS_CONF"

        cp "$TMPL_DIR/monitors.conf.template" "$MONITORS_CONF"
        MONITOR_COUNT=$(jq '.monitors | length' "$SETTINGS_FILE" 2>/dev/null)
        if [[ "$MONITOR_COUNT" -gt 0 ]]; then
            jq -r '.monitors[]? | "monitor = \(.name), \(.resW)x\(.resH)@\(.rate), \(.x)x\(.y), \(.scale)\(if .transform and .transform != 0 then ", transform, \(.transform)" else "" end)"' "$SETTINGS_FILE" >> "$MONITORS_CONF"
        else
            echo "monitor = , preferred, auto, 1" >> "$MONITORS_CONF"
        fi
    fi

    # Hash after changes
    NEW_NONMON_HASH=$(md5sum "$SETTINGS_LUA" "$KEYBINDS_LUA" "$AUTOSTART_LUA" "$ENV_LUA" \
                              "$SETTINGS_CONF" "$KEYBINDS_CONF" "$AUTOSTART_CONF" "$ENV_CONF" 2>/dev/null | md5sum)
    NEW_MON_HASH=$(md5sum "$MONITORS_LUA" "$MONITORS_CONF" 2>/dev/null | md5sum)

    # Under niri these configs aren't loaded by the compositor; config.kdl live-reloads on its own
    if [ "$OLD_MON_HASH" != "$NEW_MON_HASH" ]; then
        # Monitor layout actually changed — full reload needed
        echo "Monitor config changed, reloading Hyprland..."
        [[ -z "$NIRI_SOCKET" ]] && hyprctl reload
    elif [ "$OLD_NONMON_HASH" != "$NEW_NONMON_HASH" ]; then
        # Non-monitor settings changed (keybinds, autostart, input, env) — reload safe, no display flicker
        echo "Non-monitor config changed, reloading Hyprland..."
        [[ -z "$NIRI_SOCKET" ]] && hyprctl reload
    else
        # Nothing that affects Hyprland changed (e.g. uiScale, weatherApiKey) — skip reload entirely
        echo "No Hyprland config changes detected, skipping reload."
    fi
}

# If called with --compile, execute once and exit (used by install.sh)
if [[ "$1" == "--compile" ]]; then
    compile_settings
    exit 0
fi

echo "Started watching settings directories for changes..."

# The trailing slashes matter. ~/.config/hypr is a symlink into the dotfiles tree, and for
# a symlinked directory inotifywait's %w carries no separator of its own -- so %w%f produced
# ".../hyprsettings.json", which never equalled $SETTINGS_FILE and made every settings write
# a silent no-op. Watching "<dir>/" puts the separator in %w.
inotifywait -m -q -e close_write,moved_to --format '%w%f' \
    "$(dirname "$SETTINGS_FILE")/" "$(dirname "$ENV_FILE")/" | while read -r filepath; do

    # ---------------------------------------------------------
    # SETTINGS JSON TRIGGER
    # ---------------------------------------------------------
    if [[ "$filepath" == "$SETTINGS_FILE" ]]; then
        compile_settings
    fi

    # ---------------------------------------------------------
    # .ENV WEATHER TRIGGER
    # ---------------------------------------------------------
    if [[ "$filepath" == "$ENV_FILE" ]]; then
        echo ".env updated! Forcing weather cache refresh..."
        if [ -x "$WEATHER_SCRIPT" ]; then
            "$WEATHER_SCRIPT" --getdata &
        else
            bash "$WEATHER_SCRIPT" --getdata &
        fi
    fi
done
