[general]
mode = normal
framerate = 60
bars = 120
autosens = 1

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
channels = mono

[smoothing]
noise_reduction = 35
