-- ◈ AUTOSTART COMMANDS (AUTOGENERATED FROM SETTINGS.JSON)
return {
    "systemctl --user start hyprpolkitagent",
    "awww-daemon",
    "hypridle",
    "quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml",
    "~/.config/hypr/scripts/quickshell/focustime/launch_daemon.sh",
    "~/.config/hypr/scripts/init.sh",
    "~/.config/hypr/scripts/settings_watcher.sh &",
    "playerctld",
    "swayosd-server --top-margin 0.9 --style \"$HOME/.config/swayosd/style.css\"",
    "wl-paste --type text --watch cliphist store",
    "wl-paste --type image --watch cliphist store",
    "~/.config/hypr/scripts/volume_listener.sh",
    "~/.config/hypr/scripts/update_notifier.sh",
    "~/.config/hypr/scripts/deskicon.sh start",
    "~/.config/hypr/scripts/audioviz.sh start",
    "kdeconnect-indicator",
}
