-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ SYSTEMD GRAPHICAL SESSION (hand-written, not autogenerated)
--  Activates graphical-session.target so xdg-desktop-portal can start.
--  Without this the ScreenCast portal never comes up and screen recording
--  (gpu-screen-recorder -w portal) fails to save. exit.sh already stops it.
--
--  hyprland.start fires once per compositor launch -- this must NOT re-run on
--  `hyprctl reload`, which the settings watcher triggers on every settings change.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP DISPLAY && systemctl --user start hyprland-session.target")
end)
