foreground              #4c4f69
background              #ccd0da
selection_foreground    #dce0e8
selection_background    #df8e1d

cursor                  #1e66f5
cursor_text_color       #4c4f69

url_color               #fe640b

active_border_color     #1e66f5
inactive_border_color   #bcc0cc
bell_border_color       #d20f39

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #dce0e8
active_tab_background   #209fb5
inactive_tab_foreground #6c6f85
inactive_tab_background #ccd0da
tab_bar_background      #dce0e8

mark1_foreground #4c4f69
mark1_background #1e66f5
mark2_foreground #dce0e8
mark2_background #40a02b
mark3_foreground #4c4f69
mark3_background #fe640b

color0 #bcc0cc
color8 #5c5f77

color1 #d20f39
color9 #e64553

color2  #1e66f5
color10 #209fb5

color3  #fe640b
color11 #ea76cb

color4  #40a02b
color12 #df8e1d

color5  #209fb5
color13 #8839ef

color6  #df8e1d
color14 #ea76cb

color7  #6c6f85
color15 #4c4f69
