# Basic colors
foreground              #3C3026
background              #FFF8F4
selection_foreground    #644D36
selection_background    #FEDDBE

# Cursor colors
cursor                  #825521
cursor_text_color       #FFF7F3

# URL underline color when hovering with mouse
url_color               #5F622D

# Kitty window border colors
active_border_color     #825521
inactive_border_color   #F2DFCF
bell_border_color       #A73B21

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #623B07
active_tab_background   #FCC182
inactive_tab_foreground #6A5D50
inactive_tab_background #FCEBDE
tab_bar_background      #FFF8F4

# Colors for marks
mark1_foreground #FFF7F3
mark1_background #825521
mark2_foreground #FFF7F3
mark2_background #735B42
mark3_foreground #FBFDB9
mark3_background #5F622D

# The 16 terminal colors
# black
color0 #F2DFCF
color8 #87786B

# red
color1 #A73B21
color9 #FD795A

# green
color2  #825521
color10 #FCC182

# yellow
color3  #5F622D
color11 #FBFEBA

# blue
color4  #735B42
color12 #FEDDBE

# magenta
color5  #FCC182
color13 #FCC182

# cyan
color6  #FEDDBE
color14 #FBFEBA

# white
color7  #6A5D50
color15 #3C3026
