# Basic colors
foreground              #e4e1e9
background              #131318
selection_foreground    #e2e0f9
selection_background    #454559

# Cursor colors
cursor                  #c0c1ff
cursor_text_color       #292a60

# URL underline color when hovering with mouse
url_color               #e9b9d3

# Kitty window border colors
active_border_color     #c0c1ff
inactive_border_color   #46464f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #e1e0ff
active_tab_background   #3f4178
inactive_tab_foreground #c8c5d0
inactive_tab_background #1f1f25
tab_bar_background      #131318

# Colors for marks
mark1_foreground #292a60
mark1_background #c0c1ff
mark2_foreground #2e2f42
mark2_background #c6c4dd
mark3_foreground #46263a
mark3_background #e9b9d3

# The 16 terminal colors
# black
color0 #46464f
color8 #918f9a

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #c0c1ff
color10 #e1e0ff

# yellow
color3  #e9b9d3
color11 #ffd8ec

# blue
color4  #c6c4dd
color12 #e2e0f9

# magenta
color5  #3f4178
color13 #575992

# cyan
color6  #454559
color14 #5f3c51

# white
color7  #c8c5d0
color15 #e4e1e9
