# Basic colors
foreground              #dee3e5
background              #0e1416
selection_foreground    #cde7ed
selection_background    #334a50

# Cursor colors
cursor                  #83d2e4
cursor_text_color       #00363f

# URL underline color when hovering with mouse
url_color               #bdc5eb

# Kitty window border colors
active_border_color     #83d2e4
inactive_border_color   #3f484b
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #a3eeff
active_tab_background   #004e5a
inactive_tab_foreground #bfc8cb
inactive_tab_background #1b2122
tab_bar_background      #0e1416

# Colors for marks
mark1_foreground #00363f
mark1_background #83d2e4
mark2_foreground #1c3439
mark2_background #b2cbd1
mark3_foreground #262f4d
mark3_background #bdc5eb

# The 16 terminal colors
# black
color0 #3f484b
color8 #899295

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #83d2e4
color10 #a3eeff

# yellow
color3  #bdc5eb
color11 #dce1ff

# blue
color4  #b2cbd1
color12 #cde7ed

# magenta
color5  #004e5a
color13 #006877

# cyan
color6  #334a50
color14 #3d4565

# white
color7  #bfc8cb
color15 #dee3e5
